import type { DocumentStyleProfile } from './types';

export const DEFAULT_DOCUMENT_STYLE_PROFILE_ID = 'official-preserve';

export const documentStyleProfiles: DocumentStyleProfile[] = [
  {
    id: 'official-preserve',
    name: '공식 양식 보존',
    description: '업로드한 HWPX 양식의 표, 문단, 여백, 서명란을 우선 보존합니다.',
    mode: 'preserve-official-form',
    colors: {
      primary: '#245D50',
      primarySoft: '#F3F8F5',
      accent: '#6A9C89',
      accentSoft: '#EEF7F2',
      text: '#142033',
      muted: '#65736E',
      border: '#C5D1CC',
      surface: '#FFFFFF',
      tableHeaderBg: '#F3F7F5',
      tableHeaderText: '#24312D',
    },
    typography: {
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      titleSize: '24px',
      titleWeight: 800,
      headingWeight: 800,
      bodySize: '13px',
      lineHeight: '1.75',
    },
    section: { headingStyle: 'plain-underlined', spacing: 'normal' },
    table: { headerStyle: 'preserve', borderColor: '#C5D1CC', zebra: false, density: 'comfortable' },
    preview: {
      pageBackground: '#E2E8E5',
      documentBackground: '#FFFFFF',
      selectedOutline: '#245D50',
      note: '공식 HWPX 양식에서는 구조 변경 없이 검토 UI에만 제한 적용됩니다.',
    },
  },
  {
    id: 'university-submission',
    name: '대학 제출용',
    description: '학과, 동아리, 연구실 제출 문서에 맞춘 단정한 학술형 스타일입니다.',
    mode: 'submission',
    colors: {
      primary: '#1F4E79',
      primarySoft: '#EFF6FC',
      accent: '#4B7FA8',
      accentSoft: '#E7F0F8',
      text: '#172033',
      muted: '#5F6C7B',
      border: '#B9C9D8',
      surface: '#FFFFFF',
      tableHeaderBg: '#EAF2F8',
      tableHeaderText: '#143A5A',
    },
    typography: {
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      titleSize: '25px',
      titleWeight: 800,
      headingWeight: 800,
      bodySize: '13px',
      lineHeight: '1.8',
    },
    section: { headingStyle: 'plain-underlined', spacing: 'normal' },
    table: { headerStyle: 'tinted', borderColor: '#B9C9D8', zebra: false, density: 'comfortable' },
    preview: {
      pageBackground: '#E8EEF3',
      documentBackground: '#FFFFFF',
      selectedOutline: '#1F4E79',
      note: '제출 서류처럼 읽기 쉬운 제목 구분과 표 헤더를 적용합니다.',
    },
  },
  {
    id: 'public-agency',
    name: '공공기관 제출용',
    description: '공공기관 문서처럼 신뢰감 있고 절제된 색과 표 구성을 사용합니다.',
    mode: 'submission',
    colors: {
      primary: '#244A5A',
      primarySoft: '#EEF5F6',
      accent: '#517A85',
      accentSoft: '#E8F1F2',
      text: '#111827',
      muted: '#5D6875',
      border: '#AEBBC4',
      surface: '#FFFFFF',
      tableHeaderBg: '#EDF3F4',
      tableHeaderText: '#1E3F4E',
    },
    typography: {
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      titleSize: '24px',
      titleWeight: 800,
      headingWeight: 800,
      bodySize: '13px',
      lineHeight: '1.78',
    },
    section: { headingStyle: 'left-rule', spacing: 'normal' },
    table: { headerStyle: 'tinted', borderColor: '#AEBBC4', zebra: false, density: 'compact' },
    preview: {
      pageBackground: '#E5ECEB',
      documentBackground: '#FFFFFF',
      selectedOutline: '#244A5A',
      note: '공공기관 제출 문서에 어울리는 낮은 채도의 스타일입니다.',
    },
  },
  {
    id: 'startup-proposal',
    name: '창업지원사업 제안서형',
    description: '지원사업 제안서와 사업계획서 요약에 맞춘 명확한 강조 스타일입니다.',
    mode: 'proposal',
    colors: {
      primary: '#315E8A',
      primarySoft: '#EEF5FF',
      accent: '#2F7D6D',
      accentSoft: '#EAF7F3',
      text: '#132033',
      muted: '#5E6B7A',
      border: '#B7C9DC',
      surface: '#FFFFFF',
      tableHeaderBg: '#EAF3FC',
      tableHeaderText: '#1E4468',
    },
    typography: {
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      titleSize: '26px',
      titleWeight: 850,
      headingWeight: 800,
      bodySize: '13px',
      lineHeight: '1.75',
    },
    section: { headingStyle: 'boxed', spacing: 'wide' },
    table: { headerStyle: 'solid', borderColor: '#B7C9DC', zebra: true, density: 'comfortable' },
    preview: {
      pageBackground: '#E9EFF3',
      documentBackground: '#FFFFFF',
      selectedOutline: '#315E8A',
      note: '사업 목적, 지원 내용, 기대효과가 잘 보이도록 제목과 표 대비를 높입니다.',
    },
  },
  {
    id: 'research-plan',
    name: '연구계획서형',
    description: '연구 목적, 방법, 일정, 기대효과를 차분하게 구분하는 스타일입니다.',
    mode: 'proposal',
    colors: {
      primary: '#3E5F6F',
      primarySoft: '#EEF5F7',
      accent: '#6B7F4E',
      accentSoft: '#F0F4EA',
      text: '#142033',
      muted: '#65706C',
      border: '#BCC9C8',
      surface: '#FFFFFF',
      tableHeaderBg: '#EDF3F3',
      tableHeaderText: '#2E4B57',
    },
    typography: {
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      titleSize: '25px',
      titleWeight: 800,
      headingWeight: 800,
      bodySize: '13px',
      lineHeight: '1.82',
    },
    section: { headingStyle: 'left-rule', spacing: 'wide' },
    table: { headerStyle: 'minimal', borderColor: '#BCC9C8', zebra: true, density: 'comfortable' },
    preview: {
      pageBackground: '#E8EDEA',
      documentBackground: '#FFFFFF',
      selectedOutline: '#3E5F6F',
      note: '긴 연구계획 문단을 읽기 쉽게 여백과 행간을 넉넉히 둡니다.',
    },
  },
  {
    id: 'summary-report',
    name: '요약 보고서형',
    description: '검토용 요약본과 체크리스트를 빠르게 훑을 수 있는 보고서 스타일입니다.',
    mode: 'report',
    colors: {
      primary: '#364B63',
      primarySoft: '#F0F4F8',
      accent: '#8A6B3F',
      accentSoft: '#F7F1E7',
      text: '#162033',
      muted: '#667085',
      border: '#C4CCD5',
      surface: '#FFFFFF',
      tableHeaderBg: '#EEF2F6',
      tableHeaderText: '#263A50',
    },
    typography: {
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      titleSize: '24px',
      titleWeight: 850,
      headingWeight: 800,
      bodySize: '13px',
      lineHeight: '1.72',
    },
    section: { headingStyle: 'numbered-band', spacing: 'compact' },
    table: { headerStyle: 'solid', borderColor: '#C4CCD5', zebra: true, density: 'compact' },
    preview: {
      pageBackground: '#E7EBEF',
      documentBackground: '#FFFFFF',
      selectedOutline: '#364B63',
      note: '요약본, 체크리스트, 보고서형 산출물에 적극 적용합니다.',
    },
  },
];

export function getDocumentStyleProfile(id?: string | null): DocumentStyleProfile {
  return documentStyleProfiles.find((profile) => profile.id === id) ?? documentStyleProfiles[0]!;
}

export function isOfficialPreserveProfile(profile: DocumentStyleProfile): boolean {
  return profile.mode === 'preserve-official-form';
}

export function isStyleLimitedByOfficialForm(profile: DocumentStyleProfile, isOfficialHwpxSource: boolean): boolean {
  return isOfficialHwpxSource || isOfficialPreserveProfile(profile);
}
